### ISSUE TITLE
Issue while compiling  

### ISSUE THREAD

**Issue by deshpande67** [LDmicro/LDmicro#110]
I have issue while compile my programme with 12F683. (How to send this file to you?)

**Comment by slyshykO** [comment]
You can attach zipped *.ld to message.
![2018-05-31](https://user-images.githubusercontent.com/1575537/40769531-e3fbabce-64c0-11e8-99b8-9efaf9115597.png)

**Comment by deshpande67** [comment]
Issue is closed.
