### ISSUE TITLE
"Compile ANSIC" fails and LDmico exits with an error when the INT_SET_VARIABLE_NEG instruction is used.

### ISSUE THREAD

**Issue by GregBlackwell** [LDmicro/LDmicro#117]
Test case to demonstrate this issue:
Start the current version of LDmicro version 4.4.0.2
Create a simple program that has one rung
- Menu: Instruction -> Signed variable operations -> Insert NEG (Integer Negate)
Compile to ANSI C
- Menu: Compile -> Compile ANSIC
The "Compile To" dialog is displayed. Accept the default filename new.c
The LDmicro.exe displays an error dialog box with the text: INT_34 (ansic.cpp:1172)

My investigation into the reason for this behaviour:
In the file ansic.cpp the function GenerateDeclarations() does have a case for INT_SET_VARIABLE_NEG to generate the variable declarations but the function GenerateAnsiC() does not have a case for INT_SET_VARIABLE_NEG so it falls through to the default case which calls THROW_COMPILER_EXCEPTION_FMT() to report the error.

**Comment by LDmicroGitHub** [comment]
Fixed in Release 4.4.1.0
