### ISSUE TITLE
The code generated by "Compile ANSIC" for the Look-Up Table instruction [LUT] does not include a declaration for the table's index variable.

### ISSUE THREAD

**Issue by GregBlackwell** [LDmicro/LDmicro#124]
Test case to demonstrate this issue:
Start the current version of LDmicro version 4.4.1.0
Create a simple program that has one rung
To the first rung add the single instruction LUT
- Menu: Instruction -> Insert Look-Up Table
Double click in the LUT instruction to display the Look-Up Table dialog
Accept the default values for the Destination, Name and Index fields
Click the checkbox "Edit table of ASCII values like a string" and enter the string "Hello World!"
Review the variable definitions in the bottom pane. There are declarations for the two varables "dest" and "index" that each have the default size of two bytes.
Compile to ANSI C
- Menu: Compile -> Compile ANSIC
The "Compile To" dialog is displayed. Accept the default filename new.c

Examine the generated C program new.c
It has these variable declarations:
STATIC ldBOOL Ib_rung_top = 0;
STATIC SWORD Ui_dest = 0;
#ifdef __CODEVISIONAVR__
flash unsigned char Ui_name[12] = {72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33};
#endif
#ifdef __GNUC__
const unsigned char Ui_name[12] PROGMEM = {72, 101, 108, 108, 111, 32, 87, 111, 114, 108, 100, 33};
#endi

This is the code generated for Rung 1:
    // ======= START RUNG 1 =======
    LabelRung1:;
    Write_Ib_rung_top(1);
    // start series [
    // ELEM_LOOK_UP_TABLE name
    if(Read_Ib_rung_top()) {
        #ifdef __GNUC__
        Ui_dest = pgm_read_word(&Ui_name[Ui_index]);
        #else
        Ui_dest = Ui_name[Ui_index];
        #endif
    }
    // ] finish series

There is an SWORD variable declaration for Ui_dest.
The code for Rung 1 has a reference to the variable Ui_index that has not been declared.

**Comment by LDmicroGitHub** [comment]
Fixed in v4.4.2.0
