### ISSUE TITLE
uarto box shows up even if i deleted uart function in ladder after simulating

### ISSUE THREAD

**Issue by parksplit** [LDmicro/LDmicro#126]
hello when using uart function: 
1° simulate ladder 
2° uart box shows up 
3° stop simulation 
4° erase uart function in ladder 
5° simualte again 
6° uart box shows up again and can´t close it unless you close ldmicro 

https://www.youtube.com/watch?v=gg4U3uzljqk&feature=youtu.be

http://cq.cx/ladder-forum.pl?action=viewthread&parent=7487&tt=1532379008    (ladder)

**Comment by LDmicroGitHub** [comment]
Fixed in v4.4.2.0
