### ISSUE TITLE
ADC not sent to USART

### ISSUE THREAD

**Issue by MoinRajpoot** [LDmicro/LDmicro#130]
**Do you want to request a *feature* or report a *bug*?**

*can any one help me why UART does not sending variable data from ADC 
"
![adc not send](https://user-images.githubusercontent.com/41921640/43778509-53de1042-9a6f-11e8-94c7-d610cc4d42ae.jpg)
![adc not send](https://user-images.githubusercontent.com/41921640/43778524-5cfd3a90-9a6f-11e8-9016-2851e19ddd94.jpg)

**Comment by slyshykO** [comment]
Please, attach *.ld script. (as zip archive)

**Comment by LDmicroGitHub** [comment]
![default](https://user-images.githubusercontent.com/13471441/43823430-af3af7c4-9af7-11e8-8146-320067a9b0bb.png)  
![default](https://user-images.githubusercontent.com/13471441/43823477-cfc7e786-9af7-11e8-8755-847e0843a16d.png)

**Comment by MoinRajpoot** [comment]
ok thanks
