### ISSUE TITLE
The code generated by "Compile ANSIC" for the SRAND insyruction does not set the seed to use for subsequent pseudo-random numbers.

### ISSUE THREAD

**Issue by GregBlackwell** [LDmicro/LDmicro#133]
Test case to demonstrate this issue:
Start the current version of LDmicro version 4.4.3.0
Create a simple program that has a single rung with the single instruction SRAND
- Menu: Instruction -> Signed variable operations -> Insert Seed of Random
Double-click on the SRAND instruction to examine the default variable names
- Destination variable is "Rand" and Source is the variable "newSeed"
Compile to ANSI C
- Menu: Compile -> Compile ANSIC
The "Compile To" dialog is displayed. Accept the default filename new.c
Examine the generated program new.c
- In the INIT_VARS section the variable Ii_seed_Rand is assigned the default value of 1.
- The code for rung 1 is: Ii_seed_Rand = Ui_newSeed; 

The generated code assigns values to the seed variable Ii_seed_Rand but does not use this variable to set the seed for pseudo-random numbers. My understanding is that we need to call srand(Ii_seed_Rand) to set the new seed for the rand() function.

**Comment by LDmicroGitHub** [comment]
Will fixed in 4.4.4.0

**Comment by GregBlackwell** [comment]
This issue is fixed in the version v5.3.0.0 release
