### ISSUE TITLE
Compile as Interpretable Byte Code fails with the error: "Must choose a target microcontroller before  compiling"

### ISSUE THREAD

**Issue by GregBlackwell** [LDmicro/LDmicro#141]
Test case to demonstrate this issue:
Start the current version of LDmicro version 4.4.3.0
Create a simple program that has a single rung with the single instruction Insert Comment
- Menu: Instruction -> Insert comment
Compile to ANSI C
- Menu: Compile -> Compile Interpretable Byte Code
The "Compile To" dialog is displayed. Accept the default filename new.int
The Compile fails with the error "Must choose a target microcontroller before  compiling"

My investigation into this issue:
The function CompileProgram() in file ldmicro.cpp has this test:
    if((Prog.mcu == nullptr) && (MNU != MNU_COMPILE_PASCAL) && (MNU != MNU_COMPILE_ANSIC)
       && (MNU != MNU_COMPILE_ARDUINO) && (MNU != MNU_COMPILE_XINT)) {
        Error(_("Must choose a target microcontroller before compiling."));
        return;
    }

A case needs to be added to this test for && (MNU != MNU_COMPILE_INT).

**Comment by GregBlackwell** [comment]
This issue is resolved in release 5.3.0.0

**Comment by LDmicroGitHub** [comment]
Thank you, Greg.
The Issues, you described, are completely documented and understandable.
