### ISSUE TITLE
LDmicro 5301 does not accept MCU crystal <1MHz

### ISSUE THREAD

**Issue by LDmicroGitHub** [LDmicro/LDmicro#168]
http://cq.cx/ladder-forum.pl?action=viewthread&parent=8367&tt=1554155021

**Comment by MGPelec** [comment]
LDmicro 5301
We can not use MCU frequency's below 1MHz, it generate an error.
The internal oscillator of 500kHz is therefore not available.
Thx.

![MCU-Freq](https://user-images.githubusercontent.com/20842553/55380586-e7560700-5520-11e9-97b2-d636ccc6ef4a.jpg)

**Comment by TecnoCalubert** [comment]
El problema es que colocan (.) Cuando se tiene que colocar (, ) No hay ningun problema.
The problem is that they place (.) When it has to be placed (,) There is no problem.

**Comment by MGPelec** [comment]
I can not place a comma (,) ldmicro does not accept a (, ) only a (.)

Grtz

Op di 2 apr. 2019 om 10:57 schreef Calubert <notifications@github.com>:

**Comment by MGPelec** [comment]
It works in version 4430, so I think it's a bug.

**Comment by TecnoCalubert** [comment]
No entendí muy bien, este tema hace bastante tiempo ya se hablo de las comas y puntos y se cerro el caso

**Comment by MGPelec** [comment]
Sorry, my fault, it's no bug but my lack of knowledge of windows.
Problem solved. thx to Ihor for the  support.

I do not know if I can close this thread and how....

**Comment by LDmicroGitHub** [comment]
What value used as a "Decimal symbol" in your Windows?   
Try to change it.  
![image](https://user-images.githubusercontent.com/48811061/55424156-50249a00-5588-11e9-8551-d5e0912a7418.png)
