### ISSUE TITLE
LDmicro for ESP8266

### ISSUE THREAD

**Issue by ioeverything** [LDmicro/LDmicro#18]
develop ldmicro for esp8266. It will be so great work to compile ladder logic in esp8266

**Comment by LDmicroGitHub** [comment]
You can use ESP8266 as UART-WIFI bridge, when the module is based on the ESP8266 is connected to the existing solutions on the basis of any other microcontroller and controlled by AT-commands, providing communication solutions to the Wi-Fi infrastructure.

**Comment by LDmicroGitHub** [comment]
ESP8266 32-bit Tensilica L106-Micro Processor not in plan.

**Comment by LDmicroGitHub** [comment]
@ioeverything 
You can use ESP8266 as UART-WIFI bridge, when the module is based on the ESP8266 is connected to the existing solutions on the basis of any other microcontroller and controlled by AT-commands, providing communication solutions to the Wi-Fi infrastructure.

ESP8266 32-bit Tensilica L106-Micro Processor not in LDmicroGitHub plan.
