### ISSUE TITLE
teste

### ISSUE THREAD

**Issue by ponho** [LDmicro/LDmicro#207]
**Do you want to request a *feature* or report a *bug*?**

**What is the actual behavior?**

**If the actual behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via Google Drive(https://drive.google.com) or similar.**

**What is the expected behavior?**

**Which versions of LDmicro, and which OS are affected by this issue? Did this work in previous versions of LDmicro?**

**Comment by LDmicroGitHub** [comment]
It works. You describe a bug, then the bug will be fixed and published in the next release, then you close the issue.
