### ISSUE TITLE
PWM pin on Atmega 128

### ISSUE THREAD

**Issue by marocama** [LDmicro/LDmicro#221]
Hello!
I would like to know if there is a possibility to change the Atmega 128 PWM pin.

I verified that in any version of the software, the PWM function for the Atmega 128 is just the PB7 pin.

Is there a file that I can modify this pin or add others? In my PLC, this pin is not in the outputs, so it is useless for me.

Thank you all.

**Comment by LDmicroGitHub** [comment]
[ATMEGA128.ZIP](https://github.com/LDmicro/LDmicro/files/6176557/ATMEGA128.ZIP)
Please check PWM1C duty cycle uniformity in hardware.  
There is problem with OC1C/OC2 in Proteus ???  
![image](https://user-images.githubusercontent.com/48811061/111888353-7b5a5b00-89e4-11eb-9fae-9647a920d99c.png)
