### ISSUE TITLE
Error When Compiling

### ISSUE THREAD

**Issue by sarfat96** [LDmicro/LDmicro#29]
![1](https://cloud.githubusercontent.com/assets/25195192/26565911/7470db02-4519-11e7-9a6a-d2d40104d5ef.png)
![2](https://cloud.githubusercontent.com/assets/25195192/26565912/74785a76-4519-11e7-9ba5-34d5123cd0af.png)

When i used latest version of LDmicro (build 421) there were some errors occured when compliling, but it's okay in the previous version (build 400).

**Comment by LDmicroGitHub** [comment]
Please send the LD file to LDmicroGitHub@gmail.com
I will find cause of an error.

2017-05-30 5:32 GMT+03:00 William Sarfat <notifications@github.com>:
