### ISSUE TITLE
"Compile ANSIC" always generates a delay of 0 us no matter what delay value has been set for the DELAY instruction

### ISSUE THREAD

**Issue by GregBlackwell** [LDmicro/LDmicro#54]
Test case to demonstrate this issue:
Create a simple program that has a single rung with the single instruction DELAY
Menu: Operations that change the course of the program -> Insert Delay(us)

Set the mcu to any AVR or PIC microcontroller (to avoid the bug reported in issue #53)
Menu: Settings -> Microcontroller -> Atmel AVR ATmega2560 100-TQFP

Double click on the DELAY instruction to open the dialog box for setting the delay time.
Set a delay of 25

Compile to ANSI C
Menu: Compile -> Compile ANSIC
The "Compile To" dialog is displayed. Accept the default filename new.c

Examine the file new.ld
The DELAY instruction has 25 for the delay value.

Examine the file new.pl
The DELAY instruction has 0 for the delay value.

Examine the file new.c
The delay function calls for all the different C compilers each have 0 for the delay value.

My investigation into the reason for this behaviour:
In the file intcode.cpp in the function IntCodeFromCircuit() the case ELEM_DELAY calls the Op() function to create the entry in the IntCode[] array for the DELAY element. It only passes the value of the timer.name to the Op() function. It does not pass the value of the timer.delay to the Op() function so the literal field in the IntCode[] array element is not set and will always be the inital value of 0.

In the file ansic.cpp in the function GenerateAnsiC() the case case INT_DELAY writes the delay function calls for all the different C compilers using IntCode[i].literal as the delay value.

In the file intcode.cpp in the function IntDumpListing() the case ELEM_DELAY writes the DELAY instruction to the .pl file using IntCode[i].literal as the delay value.

In file simpledialog.cpp the function ShowDelayDialog() only includes the variable timer.name. The variable timer.delay is not passed to the delay dialog so the updated value of the delay does not get passed back from the delay dialog to update the timer.delay value in the leaf element.

**Comment by LDmicroGitHub** [comment]
v4.3.8.3
