### ISSUE TITLE
The GEQ instructrion does not work with neg.numbers

### ISSUE THREAD

**Issue by MGPelec** [LDmicro/LDmicro#57]
http://cq.cx/ladder-forum.pl?action=viewthread&parent=7125&tt=1522364256

Sorry, next time I post the issues here.

**Comment by LDmicroGitHub** [comment]
Release 4.3.9.4  
[ldmicro4394.zip](https://github.com/LDmicro/LDmicro/files/2009888/ldmicro4394.zip)  
Fixed: Try simulate GEQ.LD  
[GEQ.zip](https://github.com/LDmicro/LDmicro/files/2009849/GEQ.zip)

**Comment by MGPelec** [comment]
It's OK , I tested it...thanks
