### ISSUE TITLE
Good morning, this program in ldmicro works in simulation but it gives error (int-2001) when compiling for arduino, is it wrong how to do the program?

### ISSUE THREAD

**Issue by jafobrito** [LDmicro/LDmicro#62]
[Speed.txt](https://github.com/LDmicro/LDmicro/files/1885005/Speed.txt) Good morning, this program in ldmicro works in simulation but it gives error (int-2001) when compiling for arduino, is it wrong how to do the program?

**Do you want to request a *feature* or report a *bug*?**

**What is the actual behavior?**

**If the actual behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem via Google Drive(https://drive.google.com) or similar.**

**What is the expected behavior?**

**Which versions of LDmicro, and which OS are affected by this issue? Did this work in previous versions of LDmicro?**

**Comment by jafobrito** [comment]
Olá, o reset do PWM só acontece na transição de Xon para 1 e para 0, ou seja com duração de um tempo de ciclo mas mantendo ativado o PWM correspondente, não testei num Pic mas fiz compilação com os pinos assinalados para arduino (Atmega 328) e o erro que dá é na compilação, o que eu pretendo é ter uma saída de pulsos em que seja possível mudar a frequência de 500Hz para 1Khz na mesma saída (PWM), se ouver outra forma agradeço ajuda.

**Comment by slyshykO** [comment]
Sorry guys, but we have serious problems with PWM when compiling to C/Arduino.
It is an LDmicro bug.

**Comment by jafobrito** [comment]
Can someone explain to me how the pulse generator works in the new ldmicro,
if you can provide some examples would be better, thanks.

**Comment by LDmicroGitHub** [comment]
[speed.zip](https://github.com/LDmicro/LDmicro/files/1996913/speed.zip)
Will be fixed in Release 4.3.9.2

**Comment by LDmicroGitHub** [comment]
Please test with release 4.3.9.2 and close the issue if it is fixed.
