### ISSUE TITLE
The code generated by "Compile ANSIC" for the PWM function does not appear to be able to work.

### ISSUE THREAD

**Issue by GregBlackwell** [LDmicro/LDmicro#63]
The generated code only passes one parameter the the pwm function, the duty cycle variable. The PWM frequency and PWM resolution are not passed to the PWM function.
The value in the PWM duty cycle variable is being overwritten by the value of the PWM frequency.

Test case to demonstrate this issue:
Start the current version of LDmicro version 4.3.8.3
Create a simple program that has two rungs
The first rung has a single MOV instruction that assigns the value "50" to the variable "duty_cycle"
-Menu: Instruction -> Signed variable operations -> Insert MOV (Move)
Double-click on the MOV instruction to display the Move dialog
- Set the destination to the variable "duty_cycle" and the source to the value "50"
The second rung has a singe PWM instruction 
- Menu: Edit -> Insert Rung After
- Move to the second rung
- Menu: Instruction -> Insert Set PWM Output
Double-click on the PWM instruction to display the Set PWM Duty Cycle dialog
- Accept all the default values. The "Duty Cycle" field is the variable "duty_cycle", The "Frequency (HZ)" field is the constant "1000" and the "Resolution" field is the value "0-100% (6.7 bits)"
Compile to ANSI C
- Menu: Compile -> Compile ANSIC
The "Compile To" dialog is displayed. Accept the default filename new.c and click "Save".

Open the file new.c.
This is the code generated for Rung 2:

    // ======= START RUNG 2 =======
    LabelRung2:;
    Write_Ib_rung_top(1);
    // start series [
    // ELEM_SET_PWM
    if(Read_Ib_rung_top()) {
        Ui_duty_cycle = 1000;
        Write_Ub_PWMoutpin(Ui_duty_cycle);
        Write_Ib_PWMoutpin(1);
    }
    // ] finish series

In  the line "Ui_duty_cycle = 1000;" the value of the PWM frequency "1000" has been assigned to the variable "duty_cycle", overwriting the value of "50" that we set it to in Rung 1.
In the the line "Write_Ub_PWMoutpin(Ui_duty_cycle);" only one parameter, the duty cycle variable, is passed to the PWM function. The PWM frequency and resolution values are not passed to the PWM function. The PWM frequency and resolution values are not declared anywhere else in the generated code so the PWM function can not know what these values are.

**Comment by LDmicroGitHub** [comment]
Please test with release 4.3.9.2 and close the issue if it is fixed.
