### ISSUE TITLE
PIC10F200 compile issues

### ISSUE THREAD

**Issue by slyshykO** [LDmicro/LDmicro#65]
http://cq.cx/ladder-forum.pl?action=viewthread&parent=7194&tt=1524101599

**Comment by slyshykO** [comment]
![screenshotfrom2018-04-1821-21-28](https://user-images.githubusercontent.com/1575537/38972114-6a927b08-43a7-11e8-9637-add1a4eb21fe.png)

**Comment by LDmicroGitHub** [comment]
Fixed: Release 4.3.8.5
