### ISSUE TITLE
LDmicro not responding when compiling 

### ISSUE THREAD

**Issue by parksplit** [LDmicro/LDmicro#66]
When compiling ladder from  : 

http://cq.cx/ladder-forum.pl?action=viewthread&parent=7018&tt=1519428516

Called : "pwmexmpl_V2_with comment.ld"

Ldmicro stops responding when compiling with 328 MCU.
![1](https://user-images.githubusercontent.com/17754830/39026972-5ad90b64-4415-11e8-8d51-dc0ab7f361ff.jpg)

![2](https://user-images.githubusercontent.com/17754830/39026975-5e9ba112-4415-11e8-8a0b-601f9d028ab7.jpg)

This is the code image:

![3](https://user-images.githubusercontent.com/17754830/39027000-8064f51e-4415-11e8-8e9a-8fc4565969e4.jpg)

**Comment by slyshykO** [comment]
@MGPelec , may you check English variant of LDmicro?

**Comment by MGPelec** [comment]
I always use the English variant of LDmicro.

Gtz
MGP

2018-04-25 14:25 GMT+02:00 Slyshyk Oleksiy <notifications@github.com>:

**Comment by LDmicroGitHub** [comment]
Please test with release 4.3.9.2 and close the issue if it is fixed.

**Comment by MGPelec** [comment]
But....how do I close this issue

**Comment by slyshykO** [comment]
@MGPelec , you can't. It should be starter or owner of the repository.

**Comment by MGPelec** [comment]
I received a message to close this issue after testing and I thought.... but OK

**Comment by slyshykO** [comment]
@MGPelec , all participants in this conversation are receiving a notification.
If you no need of notification, you can unsubscribe.

**Comment by MGPelec** [comment]
It's ok I leave it so, now that I know it ... thanks for the information
