### ISSUE TITLE
When compiling ansic for arduino using REGISTER mcu, generated code includes "#", arduino doesn´t compile

### ISSUE THREAD

**Issue by parksplit** [LDmicro/LDmicro#72]
when compiling sketch for arduino and using REGISTER mcu for disabling pull up resistor, generated code contains for example "#0x55" , this symbol "#" doesn´t let arduino compile unless you delete it, see image:

![symbol_ _](https://user-images.githubusercontent.com/17754830/39280881-625f3172-48c7-11e8-9a23-87fb9f527ebe.jpg)

**Comment by LDmicroGitHub** [comment]
== Release 4.3.8.7
    * Partially fixed: When compiling ansic for arduino using REGISTER mcu,
    generated code includes "#", arduino does not compile (#72)

TODO: in many other places :(
NOTE: Do not close until full fixed.

**Comment by LDmicroGitHub** [comment]
Please test with release 4.3.9.2 and close the issue if it is fixed.
