### ISSUE TITLE
UART Simulation error  V4390

### ISSUE THREAD

**Issue by MGPelec** [LDmicro/LDmicro#84]
When I simulate this small program I get an error and  LDmicro closes. Thx

[test_uart.zip](https://github.com/LDmicro/LDmicro/files/1992207/test_uart.zip)

**Comment by TecnoCalubert** [comment]
Hola, tienes que ver que versión tienes yo lo simulo con Release 4.3.3, y me funciona perfectamente el sistema operativo también tiene que ver el XP da errores

**Comment by MGPelec** [comment]
I always use the newest version to find the bugs.

grtz



2018-05-10 19:00 GMT+02:00 Calubert <notifications@github.com>:

**Comment by LDmicroGitHub** [comment]
Fixed in 4.3.9.2
