### ISSUE TITLE
re-enable ansi C compilation with no MCU

### ISSUE THREAD

**Issue by slyshykO** [LDmicro/LDmicro#95]
It's not possible since some releases including v4.3.9.4 to generate generic ANSI-C code by selecting
"Settings-Microcontroller-(no microcontroller)"
as is was possible before! :-(
v4.3.9.4 throws an error-dialogue (see attached JPG),
v4.3.9 crashed, as i remember right... :-(

I used the hello.ld sample for testing...

Could you please re-enable this feature? ;-)

Thanx in advance... ;-) 

http://cq.cx/ladder-forum.pl?action=viewthread&parent=7336&tt=1526547419

**Comment by LDmicroGitHub** [comment]
see develop
